Add architecture overview
CosmWasm/docs-old pull request #19
Opened 2019-12-17 19:24 UTC by ethanfrey

This adds a complete section (6 pages) giving a detailed explanation of the core architectural decisions in CosmWasm. This is meant to provide a theoretical foundation to any interested developers, to complete the existing tutorial.

2019-12-17 20:03 UTC, kmw101 requested changes
Look good, nice job.

2019-12-17 20:03 UTC, kmw101 commented on docs/getting-started/intro.md
> +of rust and go, but we will lead you through, so fast learners need no prior knowledge.
Please capitalize _rust_ and _go_ to make it consistent

2019-12-17 20:03 UTC, kmw101 commented on docs/getting-started/intro.md
> +Linux or MacOS (Windows tutorial coming soon). It is helpful to have a basic understanding
I would drop _(Windows tutorial coming soon)_ in case you do't get around to it :-)

2019-12-17 20:03 UTC, kmw101 commented on docs/getting-started/intro.md
> +Going from theory to praxis, we will now get first-hand experience with CosmWasm,
You could change the "going from theory to praxis" to "Buckle up," ? Bit more punchy

2019-12-17 20:03 UTC, kmw101 commented on docs/getting-started/intro.md
> +[Editing a Contract](./editing-escrow-contract) will apply your (newly acquired) rust skills to make some changes to a sample contract.
Capitalisation of _rust_

2019-12-17 20:03 UTC, kmw101 commented on docs/intro/mutlichain.md
> +CosmWasm is designed from the ground-up to be a multi-chain solution for smart contracts.
CosmWasm is designed **and built**

2019-12-17 20:03 UTC, kmw101 commented on docs/intro/mutlichain.md
> +of blockchains, rather than silos. But what exactly do we mean by multichain?
"rather than silos" replace with "rather than the traditional blockchain silos" 

Change "multichain" to "multi-chain" for consistency

2019-12-17 20:03 UTC, kmw101 commented on docs/intro/mutlichain.md
> +Another design goal of CosmWasm was to be more of a library than a framework. This means it has a small surface area of required APIs and you can opt-in to most of the code. It is there to make life
The sentence beginning "The first is that..." should be on a new line.

2019-12-17 20:03 UTC, kmw101 commented on docs/intro/mutlichain.md
> +The second benefit is that since it makes limited demands of the host system, it can be embedded in other frameworks, not just the Cosmos SDK. The core runtime logic [`cosmwasm-vm`](https://github.co
"The core runtime logic is in *rust*" to make this consistent please use uppercase Rust.

2019-12-17 20:03 UTC, kmw101 commented on docs/intro/roadmap.md
> +Launch test net (unstable)
"test net" convention is that it is one word "testnet"?

2019-12-17 20:03 UTC, kmw101 commented on docs/intro/roadmap.md
> +- verify code, deployment, web3, etc
drop the "etc"

2019-12-17 20:03 UTC, kmw101 commented on docs/intro/roadmap.md
> +Core work to build out cosmwasm environment, and build system, example code, and cosmos sdk integration.
"cosmwasm" camelcase to make it consistent "CosmWasm"

2019-12-17 22:40 UTC, webmaster128 reviewed
very good!

2019-12-17 22:40 UTC, webmaster128 commented on docs/intro/actor.md
> +Secondly, each `Actor` can effectively run on it's own thread, with it's own queue. This both enables concurrency (which we don't make use of in CosmWasm... yet), and **serialized execution** within
2x its in "on it's own thread, with it's own queue"

2019-12-17 22:40 UTC, webmaster128 commented on docs/intro/actor.md
> +By enforcing **private internal state**, a given contract can guarantee all valid transitions in it's internal state. This is in contrast to the capabilities model used in Cosmos SDK, where trusted m
its in "it's internal state"

2019-12-17 22:40 UTC, webmaster128 commented on docs/intro/actor.md
> +
In the next section you use a contract as an actor. However, this step is missing in the general introduction. At some point we should say that we use the actor model in the way that each contract is an actor.

2019-12-17 22:40 UTC, webmaster128 commented on docs/intro/actor.md
> +As mentioned above, **serialized execution** prevents all concurrent execution of a contract's code. This is like an automatic mutex over the entire contract code. This is exactly the issue that one
missing dot in "eg deduct a balance"

2019-12-17 22:40 UTC, webmaster128 commented on docs/intro/actor.md
> +While many developers may be more comfortable thinking about directly calling the other contract in their execution path and handling the errors, you can achieve almost all the same cases with such a
missing ' in "contracts error handling code"

2019-12-17 22:40 UTC, webmaster128 commented on docs/intro/addresses.md
> +Blockchains (almost?) all use addresses to identify external actors via a hash of a public key, and many newer ones extended this to identify on-chain "smart contracts" with unique addresses as well.
missing r in "20 o 32"

2019-12-17 22:40 UTC, webmaster128 commented on docs/intro/addresses.md
> +Let's keep imagining what is possible with *Human Names*, once we develop a solution to the name service issue. We could not just use a reference to resolve a user address, but resolve a contract as
2x its in "token contract not by it's name, but by it's uniquely registered token ticker."

2019-12-18 17:14 UTC, ethanfrey commented
Thanks for the feedback, I polished up the docs a bit

2019-12-18 17:14 UTC, merged